### ISSUE TITLE
Query API

### ISSUE THREAD

**Issue by Guichaguri** [curseforge/api#3]
A Query API is an important API, it would be good for update checkers, mod installers, download buttons

Functions Included:
* Search for Projects
* Get basic information of a project
* Get project versions including the download url and the md5

Also, this API would be useful for projects that parse the page html to do the trick, like [MinecraftForum's Widget](https://github.com/minecraftforum/widget)

**Comment by prencher** [comment]
There are no current plans to expand the API in this fashion.

**Comment by lol768** [comment]
Are there any plans to develop this API further in any sort of fashion?

**Comment by prencher** [comment]
No, there are currently no plans to expand the API beyond what's required to support tool based uploads.
