### ISSUE TITLE
Filesize Limits?

### ISSUE THREAD

**Issue by phit** [curseforge/api#4]
I wrote this quick script for uploading compiled minecraft modpack server files directly to curseforge, so I can do it from my build server with way faster upload instead my home connection.

I got as response code "413 Request Too Large - Your request is too large, likely due to your upload. Please upload a smaller file, at most less than 5 Mb.", is that intentional or am I doing something wrong?

```
import requests

headers = {
    'User-Agent': 'CurseForge Uploader Script/1.0',
    'X-API-Key': 'key',
}

files = {'file': ('Server_Principium-1.0.3.zip', open('Server_Principium-1.0.3.zip', 'r'))}
data = {
    'displayName': 'PrincipiumServer_1.0.3.zip',
    'changelog': 'A plaintext string describing changes.',
    'parentFileID': '2318790',
    'releaseType': 'beta',
}

r = requests.post('https://minecraft.curseforge.com/addons/247920/upload-file', data = data, headers = headers, files = files)
print(r.status_code)
print(r.content)
```

**Comment by prencher** [comment]
You're trying to upload to `/addons`, rather than `/projects`.
