### ISSUE TITLE
Lack of a download endpoint

### ISSUE THREAD

**Issue by Anon10W1z** [curseforge/api#5]
It'd be nice if there was a way to download mod files.

**Comment by Shybella** [comment]
Actually sent an email to the guy who manages the curse widgets, I'll let you know what he says.

I'm doing this now by parsing each mod page but I don't like doing that

**Comment by lol768** [comment]
> I'm doing this now by parsing each mod page but I don't like doing that

Ironically, that's [exactly how](https://github.com/citricsquid/widget/blob/master/src/Curse.php#L83) the widget works. If a Curse employee can't get a decent API for this then I wouldn't hold your breath :P

**Comment by Shybella** [comment]
Yes, forgot to reply. He directly me to the curse widget. 

Have a look at this https://github.com/amcoder/Curse.RestProxy

**Comment by Shybella** [comment]
https://github.com/amcoder/Curse.RestProxy/wiki/Curse-Project-Feed

**Comment by prencher** [comment]
We have no current plans to expand on the API. Our priority is making it easy for authors to upload their mods. We may do so in the future.

**Comment by Shybella** [comment]
I'm using the AddOnService.svc you guys supply. That has been doing everything great.
