### ISSUE TITLE
Changelog Format

### ISSUE THREAD

**Issue by Jaliborc** [curseforge/api#7]
Currently it appears the API only accepts plaintext changelogs, unlike the website interface which accepts 3 different formats. I've been using markdown on my changelogs for years.

This by itself is not a problem. One could convert locally his own changelogs to html, using whatever syntax he/she prefers. I have tried this, by converting my markdown to html. Yet, this does not work either, as the html appears to be escaped (see https://wow.curseforge.com/projects/cursor-companion/files/2347648 for an example).

**Comment by prencher** [comment]
Hey, so this is actually supported. The documentation wasn't up to date. I've just updated it.
